language: ruby
sudo: required
dist: trusty

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.3
  - 2.6.1

before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

addons:
  chrome: stable
  firefox: latest-esr
